homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 241
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_named packages
  whitelist_external_dirs: /tmp

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: !secret http_base_url
  ssl_certificate: /etc/letsencrypt/live/todschmidt.com/fullchain.pem
  ssl_key: /etc/letsencrypt/live/todschmidt.com/privkey.pem
  trusted_networks:
    - 127.0.0.1
    - ::1
    - 192.168.1.0/24
    - 2001:DB8:ABCD::/48
  ip_ban_enabled: False
  login_attempts_threshold: 2

# # Show links to resources in log and frontend
# # introduction:
#
# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes/
#  extra_html_url:
#   - custom_ui/state-card-floorplan.html
#  javascript_version: es5
#
#
## Floorplan
#mqtt:
#binary_sensor:
#  - platform: mqtt
#    state_topic: dummy/floorplan/sensor
#    name: Floorplan
#

panel_custom:
  - name: downstairs
    sidebar_title: Downstairs
    sidebar_icon: mdi:home
    url_path: downstairs
    config: !include downstairs.yaml
  - name: upstairs
    sidebar_title: Upstairs
    sidebar_icon: mdi:home
    url_path: upstairs
    config: !include upstairs.yaml

#/Floorplan

panel_iframe:
  nodered:
    title: 'Node-Red'
    icon: 'mdi:shuffle-variant'
    url: 'https://hass.todschmidt.com:1880/'
  ide:
    title: IDE
    icon: 'mdi:code-braces'
    url: 'https://hass.todschmidt.com:1881/'
  mopidy:
    title: 'Mopidy Music'
    icon: 'mdi:music-box'
    url: 'https://hass.todschmidt.com:6683/iris/'

weather:
  - platform: darksky
    api_key: !secret dark_sky_key

tts:
  - platform: amazon_polly
    aws_access_key_id: !secret AWS_ACCESS_KEY_ID
    aws_secret_access_key: !secret AWS_SECRET_ACCESS_KEY
    profile_name: !secret AWS_PROFILE
    region_name: 'us-west-2'
    voice: Joanna

# Enables configuration UI
config:

# # Checks for available updates
# # Note: This component will send some information about your system to
# # the developers to assist with development of Home Assistant.
# # For more information, please see:
# # https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation: !include conversation.yaml

# Enables support for tracking state changes over time
history:

# # View all events in a logbook
# #logbook:
#
logger:
  default: warning
  logs:
    urllib3.connectionpool: fatal
    homeassistant.components.media_player: error
#    homeassistant.core.event: debug
    homeassistant.components.snips: debug
# #    homeassistant.helpers.script: debug
    homeassistant.helpers.intent_script: debug
# #    homeassistant.helpers.template: debug
# #    homeassistant.components.websocket_api: debug
# #    homeassistant.helpers.shell_command: debug
    homeassistant.components.mqtt: debug
# #    homeassistant.components.zha: debug
# #    homeassistant.components.sensor.zha: debug
#     homeassistant.components.http: debug
# #    homeassistant.components.device_tracker.ping: debug
# #    homeassistant.components.device_tracker.netgear: debug
# #    homeassistant.components.notify.pushbullet: debug
# #    homeassistant.components.sensor.shopping_list: debug
# #    homeassistant.components.shopping_list: debug
# #    bellows.zigbee.application: debug
# #    homeassistant.components.ios: debug
# #    homeassistant.components.media_player: debug

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# #recorder:
# #  purge_interval: 1
# #  purge_keep_days: 5
# #  db_url: sqlite:///home/homeassistant/.homeassistant/home-assistant_v2.db
# #  exclude:
# #    domains:
# #      - zwave
# #      - weblink
# #      - updater
# #    entities:
# #      - sun.sun # Don't record sun data
# #      - sensor.last_boot # Comes from 'systemmonitor' sensor platform
# #      - sensor.date
#
mqtt:
  broker: 192.168.1.201
  username: !secret mqtt_user
  password: !secret mqtt_password

zwave:
  usb_path: /dev/ttyUSB0

zha:
  usb_path: /dev/ttyUSB1
  database_path: /home/homeassistant/.homeassistant/zigbee.db

shopping_list:

ios: !include ios.yaml

climate: !include climate.yaml
automation: !include_dir_merge_list automations/
sensor: !include_dir_merge_list sensors/
device_tracker: !include device_tracker.yaml
group: !include_dir_merge_named groups/
scene: !include_dir_merge_list scenes/
camera: !include camera.yaml
light: !include light.yaml
input_boolean: !include input_boolean.yaml
input_number: !include_dir_merge_named input_number/
binary_sensor: !include binary_sensor.yaml
shell_command: !include_dir_merge_named shell_command/
media_player: !include media_player.yaml
switch: !include_dir_merge_list switch/
notify: !include notify.yaml
script: !include_dir_merge_named scripts/
cover: !include cover.yaml
zone: !include zone.yaml
#
# Custom
#variable: !include variables.yaml
snips:
  probability_threshold: 0.30
  feedback_sounds: true
  site_ids:
    - default
    - remote

intent_script: !include_dir_merge_named intent_scripts
#android_ip_webcam: !include android_ip_webcam.yaml
